service: user-sync

custom:
  kualiApiKey: ${ssm:monsters_key}
  userTable: users
  institution: monsters

plugins:
  - serverless-offline

provider:
  name: aws
  runtime: nodejs6.10
  region: us-west-2
  profile: kuali-dev
  iamRoleStatements:
    - Effect: Allow
      Action:
        - dynamodb:BatchWriteItem
      Resource: 'arn:aws:dynamodb:${self:provider.region}:*:*'

functions:
  sync:
    handler: handler.sync
    events:
      - schedule: rate(24 hours)
      - http: GET /
    environment:
      apiKey: ${self:custom.kualiApiKey}
      institution: ${self:custom.institution}
      table: ${self:custom.userTable}

resources:
 Resources:
   UserTable:
     Type: AWS::DynamoDB::Table
     Properties:
       TableName: ${self:custom.userTable}
       KeySchema:
         - AttributeName: id
           KeyType: HASH
       AttributeDefinitions:
         - AttributeName: id
           AttributeType: S
       ProvisionedThroughput:
         ReadCapacityUnits: 5
         WriteCapacityUnits: 5
